---
- name: Set authorized key
  authorized_key:
    user: "{{ssh_user}}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tags:
    - setup

- name: Install dev tools
  apt: pkg={{item}} state=latest update_cache=yes
  with_items:
    - openssl
    - python
    - python-pip
    - python-dev
    - build-essential
  sudo: yes
  tags:
    - setup
