- name: Install PHP
  apt: pkg={{item}} state=latest update_cache=yes
  with_items:
    - php
    - libapache2-mod-php
    - php-mcrypt
    - php-mysql
    - php-cli
    - php-curl
    - php-gd
    - php-mbstring
    - php-xml
    - php-xmlrpc
  sudo: yes
  tags:
    - setup

- name: Download wp-cli
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp

- name: Install wp-cli
  file:
    path: /usr/local/bin/wp
    mode: 0755
